packages:
  - 'apps/*'
  - 'packages/*'
catalog:
  'react': '^19'
  'react-dom': '^19'
  '@types/react': '^19'
  '@types/react-dom': '^19'
  '@vitejs/plugin-react': '^6.0.1'
  'tailwind-variants': '^3.2.2'
  'tailwindcss': '^4.2.1'
  'vite': '^8.0.10'
  'zustand': '^5.0.11'
