export const AUTH_STATES = {
	INITIALIZING: 'initializing',
	UNAUTHENTICATED: 'unauthenticated',
	AUTHENTICATED: 'authenticated',
	ERROR: 'error',
} as const

export const AUTH_EVENTS = {
	INITIALIZATION_STARTED: 'INITIALIZATION_STARTED',
	USER_LOADED: 'USER_LOADED',
	SIGN_IN_STARTED: 'SIGN_IN_STARTED',
	SIGN_IN_SUCCEEDED: 'SIGN_IN_SUCCEEDED',
	SIGN_IN_FAILED: 'SIGN_IN_FAILED',
	SIGN_OUT_STARTED: 'SIGN_OUT_STARTED',
	SIGN_OUT_SUCCEEDED: 'SIGN_OUT_SUCCEEDED',
	SIGN_OUT_FAILED: 'SIGN_OUT_FAILED',
	AUTH_ERROR: 'AUTH_ERROR',
} as const

export const MIN_PASSWORD_LENGTH = 8
export const MAX_PASSWORD_LENGTH = 72
