import { formatFiles, installPackagesTask, type Tree } from '@nx/devkit'

interface RenameScopeGeneratorSchema {
	name: string
	from?: string
}

const DEFAULT_FROM = 'thom'

/** Generated artefacts and binaries: rewriting these is either useless or destructive. */
const IGNORED_DIRS = new Set(['node_modules', '.git', '.next', '.nx', 'dist', '.vercel', '.turbo'])

/**
 * The lockfile is regenerated by `pnpm install`, and rewriting it by hand
 * desynchronises the integrity hashes from the registry tarballs.
 */
const IGNORED_FILES = new Set(['pnpm-lock.yaml'])

/**
 * This generator's own source: its scope tokens are the rename logic itself,
 * so rewriting them would leave the illustrative comments self-referential and
 * break a second run by mutating DEFAULT_FROM.
 */
const SELF = 'packages/workspace-tools/generators/rename-scope/generator.ts'

const TEXT_EXTENSIONS = new Set([
	'.ts',
	'.tsx',
	'.js',
	'.jsx',
	'.mjs',
	'.cjs',
	'.json',
	'.jsonc',
	'.md',
	'.mdx',
	'.css',
	'.yaml',
	'.yml',
	'.toml',
	'.html',
	'.txt',
])

const extensionOf = (path: string): string => {
	const slash = path.lastIndexOf('/')
	const dot = path.lastIndexOf('.')
	return dot > slash ? path.slice(dot) : ''
}

const isRenameable = (path: string): boolean => {
	if (path === SELF) return false

	const fileName = path.slice(path.lastIndexOf('/') + 1)
	if (IGNORED_FILES.has(fileName)) return false
	return TEXT_EXTENSIONS.has(extensionOf(path))
}

/** Escapes a string for literal use inside a RegExp. */
const escape = (value: string): string => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')

/**
 * Collects every renameable file, skipping ignored directories entirely so the
 * walk never descends into node_modules.
 */
const collectFiles = (tree: Tree, dir: string): string[] => {
	const found: string[] = []

	for (const child of tree.children(dir)) {
		if (IGNORED_DIRS.has(child)) continue

		const path = dir === '.' ? child : `${dir}/${child}`

		if (!tree.isFile(path)) {
			found.push(...collectFiles(tree, path))
			continue
		}

		if (isRenameable(path)) found.push(path)
	}

	return found
}

export default async function renameScopeGenerator(tree: Tree, options: RenameScopeGeneratorSchema) {
	const from = options.from ?? DEFAULT_FROM
	const to = options.name

	if (to === from) {
		throw new Error(`The new scope "${to}" is identical to the current scope "${from}".`)
	}

	if (!/^[a-z0-9][a-z0-9-]*$/.test(to)) {
		throw new Error(`"${to}" is not a valid npm scope. Use lowercase letters, digits and hyphens.`)
	}

	const replacements: Array<[RegExp, string]> = [
		// Package scope: @thom/ui -> @acme/ui
		[new RegExp(`@${escape(from)}/`, 'g'), `@${to}/`],
		// Component DOM hooks: data-id='thom-ui' -> data-id='acme-ui'
		[new RegExp(`(?<=data-id=['"\`])${escape(from)}-ui`, 'g'), `${to}-ui`],
	]

	const changed: string[] = []

	for (const path of collectFiles(tree, '.')) {
		const before = tree.read(path, 'utf-8')
		if (!before) continue

		const after = replacements.reduce((text, [pattern, value]) => text.replace(pattern, value), before)

		if (after !== before) {
			tree.write(path, after)
			changed.push(path)
		}
	}

	renameRootPackage(tree, from, to)
	renameCogRepository(tree, from, to)

	await formatFiles(tree)

	console.info(`\nRenamed @${from} to @${to} across ${changed.length} files.`)

	// The lockfile and the node_modules links still point at the old scope, and
	// nx cannot resolve its own plugins until pnpm has relinked them. The
	// install is forced because it is otherwise skipped unless the root
	// package.json itself changed.
	return () => {
		installPackagesTask(tree, true)
	}
}

/** The root package name is a bare string, not a scoped one, so it needs an exact match. */
const renameRootPackage = (tree: Tree, from: string, to: string) => {
	const path = 'package.json'
	const raw = tree.read(path, 'utf-8')
	if (!raw) return

	const json = JSON.parse(raw)
	if (json.name !== from) return

	json.name = to
	tree.write(path, `${JSON.stringify(json, null, '\t')}\n`)
}

/** cog.toml carries the repository name used to build changelog links. */
const renameCogRepository = (tree: Tree, from: string, to: string) => {
	const path = 'cog.toml'
	const raw = tree.read(path, 'utf-8')
	if (!raw) return

	const updated = raw.replace(new RegExp(`^(repository\\s*=\\s*)"${escape(from)}"$`, 'm'), `$1"${to}"`)

	if (updated !== raw) tree.write(path, updated)
}
